// apps/chat/src/components/Navigator.vue
<script lang="ts" setup></script>

<template>
  <nav
    class="fixed right-20 bottom-20 flex border border-solid border-gray-200 shadow-sm"
  >
    <router-link class="block p-4 hover:bg-gray-50" to="/">Home</router-link>
    <router-link class="block p-4 hover:bg-gray-50" to="/room/sm"
      >Room</router-link
    >
  </nav>
</template>

// apps/labs/src/lib/modules/navigator/navigator.svelte
<script lang="ts">
  export const count = 0;
</script>

<nav class="absolute right-5 top-5 z-20">
  <ul class="flex items-center justify-center gap-1">
    <li class="block">
      <a href="/">Home</a>
    </li>
    <li class="block">
      <a href="/mobile">Mobile</a>
    </li>
  </ul>
</nav>

<style lang="sass">
ul li a
    @apply px-2 py-1 cursor-pointer bg-gray-100 border border-solid border-gray-200 rounded
</style>
